### ISSUE TITLE
Workspace not deleting properly

### ISSUE THREAD

**Issue by thatsk** [AzBuilder/terrakube#435] opened 2023-07-06 12:48 UTC
### Bug description 🐞

When I delete workspace create same workspace it is not creating with same id.

### Steps to reproduce

start with docker-compose.
go to simple workspace.
create some git based repo workflow. and delete and recreate with same name.

### Expected behavior

it should create workspace with same name after deleting also.

**Comment by alfespa17** [comment] 2023-07-06 15:07
Hello @thatsk this is not a bug, it is working as expected, there is a unique constraint in the database base on organization_id, name in this file:

https://github.com/AzBuilder/terrakube/blob/main/api/src/main/resources/db/changelog/local/changelog-1.1.xml#L24

When you delete a workspace we are using a "sof delete", we dont delete the record from the database.

If you are creating a lot of workspaces what you can do is just adding some random "suffix" in the name and that should help to avoid the unique constraint restriction.

**Comment by thatsk** [comment] 2023-07-06 15:17
But even if we need to delete that it should delete it why we are keeping old records in database.

**Comment by alfespa17** [comment] 2023-07-06 15:36
It is a good practice to use "soft delete" for auditing purposes when you are deploying a lot of workspaces in different organizations.

**Comment by alfespa17** [comment] 2023-07-11 21:15
I will close this issue because it is working as expected

**Closed by alfespa17** 2023-07-11 21:15 UTC
Labels: bug
